schema_version: 1

context:
  name: vaspparser
  version: 0.0.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 23a4bedb6c9b2ffec2026a46f44c8792f033b7a2d2767de26c0d126eafc5fb5a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - ase
    - defusedxml
    - numpy
    - pandas
    - scipy
  run:
    - python >=${{ python_min }}
    - ase >=3.23.0,<=3.29.0
    - defusedxml >=0.7.0,<=0.7.1
    - numpy >=1.26.0,<=2.4.6
    - pandas >=2.0.3,<=3.0.3
    - scipy >=1.11.1,<=1.17.1
tests:
  - python:
      imports:
        - vaspparser
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Parser for the Vienna Ab initio Simulation Package (VASP)
  homepage: https://github.com/pyiron/vaspparser

extra:
  recipe-maintainers:
    - jan-janssen
